apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: testkube

resources:
  - testkube-watch-controller.yaml

images:
  - name: testkube-watch-controller
    newName: lreimer/testkube-watch-controller
    newTag: latest

configMapGenerator:
  - name: testkube-watch
    files:
      - .testkube-watch.yaml