apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  labels:
    app.kubernetes.io/name: nginx
    testkube.io/enabled: "true"
  annotations:
    testkube.io/test-suite: nginx-curl-testsuite
    testkube.io/namespace: testkube
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: http 
  selector:
    app: nginx